import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PLANTS_DIR = path.join(__dirname, "../public/plants");
const OUTPUT = path.join(__dirname, "../app/data/plants.ts");

const IMAGE_EXT = /\.(jpg|jpeg|png|webp|gif)$/i;

const CATEGORY_CONFIG = {
  "tc-tubs": { label: "TC Tubs", order: 1 },
  potted: { label: "Potted Plants", order: 2 },
  bunches: { label: "Bunches", order: 3 },
  gallery: { label: "Gallery", order: 4 },
  mosses: { label: "Mosses", order: 5 },
};

function slugify(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function parseName(filename) {
  const base = filename.replace(IMAGE_EXT, "").trim();

  const codedMatch = base.match(
    /^(PP|TC|MO|M0|bunch|bunches)\s*(\d+\s*)?(.*)$/i,
  );
  if (codedMatch) {
    const prefix = codedMatch[1].toUpperCase();
    const num = codedMatch[2]?.trim() ?? "";
    const code = num ? `${prefix} ${num}`.trim() : prefix;
    const remainder = codedMatch[3]?.trim() ?? "";

    if (remainder) {
      return { code, name: remainder };
    }

    return { code, name: code };
  }

  return { code: "", name: base };
}

function formatSubcategoryLabel(value) {
  return value
    .split(/[-_/]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function scanCategory(categoryDir, category, subcategory = null) {
  const plants = [];
  const entries = fs.readdirSync(categoryDir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(categoryDir, entry.name);

    if (entry.isDirectory()) {
      const nextSubcategory = subcategory
        ? `${subcategory}/${entry.name}`
        : entry.name;
      plants.push(...scanCategory(fullPath, category, nextSubcategory));
      continue;
    }

    if (!IMAGE_EXT.test(entry.name)) {
      continue;
    }

    const { code, name } = parseName(entry.name);
    const relativePath = `/plants/${path
      .relative(PLANTS_DIR, fullPath)
      .split(path.sep)
      .join("/")}`;

    plants.push({
      id: slugify(`${category}-${subcategory ?? "root"}-${code}-${name}`),
      name,
      code,
      category,
      subcategory,
      imagePath: relativePath,
    });
  }

  return plants;
}

function getPottedSubcategories(plants) {
  const subcategories = new Set();

  for (const plant of plants) {
    if (plant.category !== "potted") {
      continue;
    }

    if (!plant.subcategory) {
      subcategories.add("other");
      continue;
    }

    const parts = plant.subcategory.split("/");
    if (parts[0] === "terarium" && parts[1]) {
      subcategories.add(parts[1]);
      continue;
    }

    subcategories.add(parts[0]);
  }

  return [...subcategories]
    .sort((a, b) => {
      if (a === "other") return 1;
      if (b === "other") return -1;
      return a.localeCompare(b);
    })
    .map((id) => ({
      id,
      label: id === "other" ? "Other" : formatSubcategoryLabel(id),
    }));
}

const categoryDirs = fs
  .readdirSync(PLANTS_DIR, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort(
    (a, b) =>
      (CATEGORY_CONFIG[a]?.order ?? 99) - (CATEGORY_CONFIG[b]?.order ?? 99),
  );

const plants = categoryDirs.flatMap((category) =>
  scanCategory(path.join(PLANTS_DIR, category), category),
);

const categories = categoryDirs.map((id) => ({
  id,
  label: CATEGORY_CONFIG[id]?.label ?? id,
  order: CATEGORY_CONFIG[id]?.order ?? 99,
}));

const pottedSubcategories = getPottedSubcategories(plants);

const output = `// Auto-generated by scripts/generate-catalog.mjs — do not edit manually

import type { CategoryConfig, Plant } from "./types";

export const categories: CategoryConfig[] = ${JSON.stringify(categories, null, 2)};

export const pottedSubcategories = ${JSON.stringify(pottedSubcategories, null, 2)};

export const plants: Plant[] = ${JSON.stringify(plants, null, 2)};
`;

fs.writeFileSync(OUTPUT, output);
console.log(`Generated ${plants.length} plants across ${categories.length} categories.`);
