// Auto-generated by scripts/generate-catalog.mjs — do not edit manually

import type { CategoryConfig, Plant } from "./types";

export const categories: CategoryConfig[] = [
  {
    "id": "tc-tubs",
    "label": "TC Tubs",
    "order": 1
  },
  {
    "id": "potted",
    "label": "Potted Plants",
    "order": 2
  },
  {
    "id": "bunches",
    "label": "Bunches",
    "order": 3
  },
  {
    "id": "gallery",
    "label": "Gallery",
    "order": 4
  },
  {
    "id": "mosses",
    "label": "Mosses",
    "order": 5
  }
];

export const pottedSubcategories = [
  {
    "id": "alternanthera",
    "label": "Alternanthera"
  },
  {
    "id": "anubias",
    "label": "Anubias"
  },
  {
    "id": "bacopa",
    "label": "Bacopa"
  },
  {
    "id": "cabumba",
    "label": "Cabumba"
  },
  {
    "id": "cryptocoryne",
    "label": "Cryptocoryne"
  },
  {
    "id": "dracena",
    "label": "Dracena"
  },
  {
    "id": "echinodorus",
    "label": "Echinodorus"
  },
  {
    "id": "hydrocotyle",
    "label": "Hydrocotyle"
  },
  {
    "id": "Hygrophilla",
    "label": "Hygrophilla"
  },
  {
    "id": "ludwigia",
    "label": "Ludwigia"
  },
  {
    "id": "ophiopogon",
    "label": "Ophiopogon"
  },
  {
    "id": "rotala",
    "label": "Rotala"
  },
  {
    "id": "syngonium",
    "label": "Syngonium"
  },
  {
    "id": "other",
    "label": "Other"
  }
];

export const plants: Plant[] = [
  {
    "id": "tc-tubs-root-tc-17-anubias-barteri",
    "name": "Anubias barteri",
    "code": "TC 17",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC  17 Anubias barteri.jpg"
  },
  {
    "id": "tc-tubs-root-tc-01-hydrocotyle-tripartita-japan",
    "name": "Hydrocotyle tripartita Japan",
    "code": "TC 01",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 01 Hydrocotyle tripartita Japan.jpg"
  },
  {
    "id": "tc-tubs-root-tc-02-staurogyne-repens",
    "name": "Staurogyne repens",
    "code": "TC 02",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 02    Staurogyne repens.jpg"
  },
  {
    "id": "tc-tubs-root-tc-03-elecharis-aciculris-mini",
    "name": "Elecharis aciculris mini",
    "code": "TC 03",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 03   Elecharis aciculris mini.jpg"
  },
  {
    "id": "tc-tubs-root-tc-04-alternanthera-reineckii-mini",
    "name": "Alternanthera reineckii Mini",
    "code": "TC 04",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 04   Alternanthera reineckii Mini.jpg"
  },
  {
    "id": "tc-tubs-root-tc-05-hygrophila-polysperma-rosanervig",
    "name": "Hygrophila polysperma rosanervig",
    "code": "TC 05",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 05  Hygrophila polysperma rosanervig.jpg"
  },
  {
    "id": "tc-tubs-root-tc-06-hygrophila-pinnatifida",
    "name": "Hygrophila pinnatifida",
    "code": "TC 06",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 06  Hygrophila pinnatifida.jpg"
  },
  {
    "id": "tc-tubs-root-tc-08-ludwigia-ovalis",
    "name": "Ludwigia ovalis",
    "code": "TC 08",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 08   Ludwigia ovalis.jpg"
  },
  {
    "id": "tc-tubs-root-tc-09-hygrophila-lancea-araguaia",
    "name": "Hygrophila lancea Araguaia",
    "code": "TC 09",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 09  Hygrophila lancea Araguaia.jpg"
  },
  {
    "id": "tc-tubs-root-tc-10-rorippa-aquatica",
    "name": "Rorippa aquatica",
    "code": "TC 10",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 10    Rorippa aquatica.jpg"
  },
  {
    "id": "tc-tubs-root-tc-11-cryptocoryne-wendtii-red",
    "name": "Cryptocoryne wendtii Red",
    "code": "TC 11",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 11  Cryptocoryne wendtii Red.jpg"
  },
  {
    "id": "tc-tubs-root-tc-12-cryptocoryne-beckettii",
    "name": "Cryptocoryne beckettii",
    "code": "TC 12",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 12    Cryptocoryne beckettii.jpg"
  },
  {
    "id": "tc-tubs-root-tc-13-micranthemum-callitrichoides",
    "name": "Micranthemum callitrichoides",
    "code": "TC 13",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 13    Micranthemum callitrichoides.jpg"
  },
  {
    "id": "tc-tubs-root-tc-14-cryptocoryne-parva",
    "name": "Cryptocoryne parva",
    "code": "TC 14",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 14  Cryptocoryne parva.jpg"
  },
  {
    "id": "tc-tubs-root-tc-15-cryptocoryne-wendtii-green",
    "name": "Cryptocoryne wendtii  green",
    "code": "TC 15",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 15    Cryptocoryne wendtii  green.jpg"
  },
  {
    "id": "tc-tubs-root-tc-16-anubias-nana",
    "name": "Anubias nana",
    "code": "TC 16",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 16   Anubias nana.jpg"
  },
  {
    "id": "tc-tubs-root-tc-18-anubias-hasitifolia",
    "name": "Anubias hasitifolia",
    "code": "TC 18",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 18   Anubias hasitifolia.jpg"
  },
  {
    "id": "tc-tubs-root-tc-19-anubias-nana-nangi",
    "name": "Anubias nana nangi",
    "code": "TC 19",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 19  Anubias nana nangi.jpg"
  },
  {
    "id": "tc-tubs-root-tc-20-cryptocoryne-pygmea",
    "name": "Cryptocoryne pygmea",
    "code": "TC 20",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 20 Cryptocoryne pygmea.jpg"
  },
  {
    "id": "tc-tubs-root-tc-21-cryptocoryne-lutea",
    "name": "Cryptocoryne lutea",
    "code": "TC 21",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 21 Cryptocoryne lutea.jpg"
  },
  {
    "id": "tc-tubs-root-tc-23-pogostemon-erectus",
    "name": "Pogostemon erectus",
    "code": "TC 23",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 23  Pogostemon erectus.jpg"
  },
  {
    "id": "tc-tubs-root-tc-25-limnophila-sessiliflora",
    "name": "Limnophila sessiliflora",
    "code": "TC 25",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 25  Limnophila sessiliflora.jpg"
  },
  {
    "id": "tc-tubs-root-tc-26-bacopa-monnieri",
    "name": "Bacopa monnieri",
    "code": "TC 26",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 26   Bacopa monnieri.jpg"
  },
  {
    "id": "tc-tubs-root-tc-27-bacopa-caroliniana",
    "name": "Bacopa caroliniana",
    "code": "TC 27",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 27  Bacopa caroliniana.jpg"
  },
  {
    "id": "tc-tubs-root-tc-29-cryptocoryne-wenditii-brown",
    "name": "Cryptocoryne wenditii brown",
    "code": "TC 29",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 29   Cryptocoryne wenditii brown.jpg"
  },
  {
    "id": "tc-tubs-root-tc-30-cryptcoryne-beckettii-green-dsc0670",
    "name": "Cryptcoryne beckettii 'Green'DSC0670",
    "code": "TC 30",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 30    Cryptcoryne beckettii 'Green'DSC0670.jpg"
  },
  {
    "id": "tc-tubs-root-tc-31-micranthemum-micramanthoides",
    "name": "Micranthemum micramanthoides",
    "code": "TC 31",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 31    Micranthemum micramanthoides.jpg"
  },
  {
    "id": "tc-tubs-root-tc-32-cryptocoryne-petchii-green",
    "name": "Cryptocoryne petchii green",
    "code": "TC 32",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 32    Cryptocoryne petchii green.jpg"
  },
  {
    "id": "tc-tubs-root-tc-33-cryptocoryne-petchii",
    "name": "Cryptocoryne petchii",
    "code": "TC 33",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 33     Cryptocoryne petchii   .jpg"
  },
  {
    "id": "tc-tubs-root-tc-34-cryptocoryne-wendtii-mioya",
    "name": "Cryptocoryne wendtii Mioya",
    "code": "TC 34",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 34  Cryptocoryne wendtii Mioya.jpg"
  },
  {
    "id": "tc-tubs-root-tc-35-echinodorus-latifolius",
    "name": "Echinodorus latifolius",
    "code": "TC 35",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 35     Echinodorus latifolius.jpg"
  },
  {
    "id": "tc-tubs-root-tc-36-alternanthera-reineckii",
    "name": "Alternanthera reineckii",
    "code": "TC 36",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 36   Alternanthera reineckii .jpg"
  },
  {
    "id": "tc-tubs-root-tc-37-cryptocoryne-wendtii-broad-leaf",
    "name": "Cryptocoryne wendtii Broad Leaf",
    "code": "TC 37",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 37  Cryptocoryne wendtii Broad Leaf.jpg"
  },
  {
    "id": "tc-tubs-root-tc-40-alternanthera-reineckii-mini-kerala",
    "name": "Alternanthera reineckii Mini Kerala",
    "code": "TC 40",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 40  Alternanthera reineckii Mini Kerala.jpg"
  },
  {
    "id": "tc-tubs-root-tc-41-rotala-bonsai",
    "name": "Rotala bonsai",
    "code": "TC 41",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 41   Rotala bonsai.jpg"
  },
  {
    "id": "tc-tubs-root-tc-42-liliopsis-brasiliensis",
    "name": "Liliopsis brasiliensis",
    "code": "TC 42",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 42  Liliopsis brasiliensis.jpg"
  },
  {
    "id": "tc-tubs-root-tc-43-elecharis-parvula",
    "name": "Elecharis parvula",
    "code": "TC 43",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 43   Elecharis parvula.jpg"
  },
  {
    "id": "tc-tubs-root-tc-44-lobelia-cardinalis",
    "name": "Lobelia cardinalis",
    "code": "TC 44",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 44    Lobelia cardinalis.jpg"
  },
  {
    "id": "tc-tubs-root-tc-45-rotala-rotundifolia",
    "name": "Rotala rotundifolia",
    "code": "TC 45",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 45  Rotala rotundifolia  .jpg"
  },
  {
    "id": "tc-tubs-root-tc-46-glossasitgma-elatinoides",
    "name": "Glossasitgma elatinoides",
    "code": "TC 46",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 46   Glossasitgma elatinoides.jpg"
  },
  {
    "id": "tc-tubs-root-tc-48-micranthemum-monte-carlo",
    "name": "Micranthemum monte carlo",
    "code": "TC 48",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 48   Micranthemum monte carlo.jpg"
  },
  {
    "id": "tc-tubs-root-tc-50-lagadandra-thwaitesii",
    "name": "Lagadandra thwaitesii",
    "code": "TC 50",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 50  Lagadandra thwaitesii.jpg"
  },
  {
    "id": "tc-tubs-root-tc-51-alternanthera-reineckii-rosifolia",
    "name": "Alternanthera reineckii  Rosifolia",
    "code": "TC 51",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 51  Alternanthera reineckii  Rosifolia.jpg"
  },
  {
    "id": "tc-tubs-root-tc-52-rotala-rotundifolia-red",
    "name": "Rotala rotundifolia red",
    "code": "TC 52",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 52   Rotala rotundifolia red.jpg"
  },
  {
    "id": "tc-tubs-root-tc-53-ludwigia-super-red",
    "name": "Ludwigia super red",
    "code": "TC 53",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 53   Ludwigia super red.jpg"
  },
  {
    "id": "tc-tubs-root-tc-54-cryptocoryne-flamingo",
    "name": "Cryptocoryne flamingo",
    "code": "TC 54",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 54     Cryptocoryne flamingo.jpg"
  },
  {
    "id": "tc-tubs-root-tc-55-limnophila-aromatica",
    "name": "Limnophila aromatica",
    "code": "TC 55",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 55   Limnophila aromatica.jpg"
  },
  {
    "id": "tc-tubs-root-tc-56-ludwigia-aracuta-red",
    "name": "Ludwigia aracuta red",
    "code": "TC 56",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 56   Ludwigia aracuta red.jpg"
  },
  {
    "id": "tc-tubs-root-tc-57-proserpinaca-pulustris",
    "name": "Proserpinaca pulustris",
    "code": "TC 57",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 57    Proserpinaca pulustris.jpg"
  },
  {
    "id": "tc-tubs-root-tc-58-ludwigia-brevis",
    "name": "Ludwigia brevis",
    "code": "TC 58",
    "category": "tc-tubs",
    "subcategory": null,
    "imagePath": "/plants/tc-tubs/TC 58    Ludwigia brevis.jpg"
  },
  {
    "id": "potted-alternanthera-pp-04-alternanthera-rosifolia",
    "name": "Alternanthera rosifolia",
    "code": "PP 04",
    "category": "potted",
    "subcategory": "alternanthera",
    "imagePath": "/plants/potted/alternanthera/PP 04    Alternanthera rosifolia.jpg"
  },
  {
    "id": "potted-alternanthera-pp-108-alternanthera-cardinalis",
    "name": "Alternanthera cardinalis",
    "code": "PP 108",
    "category": "potted",
    "subcategory": "alternanthera",
    "imagePath": "/plants/potted/alternanthera/PP 108  Alternanthera cardinalis.jpg"
  },
  {
    "id": "potted-alternanthera-pp-147-alternanthera-liliensis",
    "name": "Alternanthera liliensis",
    "code": "PP 147",
    "category": "potted",
    "subcategory": "alternanthera",
    "imagePath": "/plants/potted/alternanthera/PP 147    Alternanthera liliensis.jpg"
  },
  {
    "id": "potted-alternanthera-pp-158-alternanthera-reineckii-mini",
    "name": "Alternanthera reineckii mini",
    "code": "PP 158",
    "category": "potted",
    "subcategory": "alternanthera",
    "imagePath": "/plants/potted/alternanthera/PP 158   Alternanthera reineckii mini.jpg"
  },
  {
    "id": "potted-alternanthera-pp-84-alternanthera-bettzickiana-red",
    "name": "Alternanthera bettzickiana red",
    "code": "PP 84",
    "category": "potted",
    "subcategory": "alternanthera",
    "imagePath": "/plants/potted/alternanthera/PP 84    Alternanthera bettzickiana red.jpg"
  },
  {
    "id": "potted-alternanthera-pp-85-alternanthera-bettzickiana-green",
    "name": "Alternanthera bettzickiana green",
    "code": "PP 85",
    "category": "potted",
    "subcategory": "alternanthera",
    "imagePath": "/plants/potted/alternanthera/PP 85    Alternanthera bettzickiana green.jpg"
  },
  {
    "id": "potted-anubias-pp-100-anubias-nana",
    "name": "Anubias nana",
    "code": "PP 100",
    "category": "potted",
    "subcategory": "anubias",
    "imagePath": "/plants/potted/anubias/PP 100 Anubias nana.jpg"
  },
  {
    "id": "potted-anubias-pp-101-anubias-hastifolia",
    "name": "Anubias hastifolia",
    "code": "PP 101",
    "category": "potted",
    "subcategory": "anubias",
    "imagePath": "/plants/potted/anubias/PP 101   Anubias hastifolia.jpg"
  },
  {
    "id": "potted-anubias-pp-102-anubias-barteri-var-barteri",
    "name": "Anubias barteri var barteri",
    "code": "PP 102",
    "category": "potted",
    "subcategory": "anubias",
    "imagePath": "/plants/potted/anubias/PP 102   Anubias barteri var barteri.jpg"
  },
  {
    "id": "potted-anubias-pp-155-anubias-conegensis",
    "name": "Anubias conegensis",
    "code": "PP 155",
    "category": "potted",
    "subcategory": "anubias",
    "imagePath": "/plants/potted/anubias/PP 155    Anubias conegensis.jpg"
  },
  {
    "id": "potted-anubias-pp-168-anubias-barteri-round-leaf",
    "name": "Anubias barteri round leaf",
    "code": "PP 168",
    "category": "potted",
    "subcategory": "anubias",
    "imagePath": "/plants/potted/anubias/PP 168   Anubias barteri round leaf.jpg"
  },
  {
    "id": "potted-anubias-pp-171-anubias-undulatus",
    "name": "Anubias undulatus",
    "code": "PP 171",
    "category": "potted",
    "subcategory": "anubias",
    "imagePath": "/plants/potted/anubias/PP 171  Anubias undulatus.jpg"
  },
  {
    "id": "potted-anubias-pp-172-anubias-bartei-broad-leaf",
    "name": "Anubias bartei broad leaf",
    "code": "PP 172",
    "category": "potted",
    "subcategory": "anubias",
    "imagePath": "/plants/potted/anubias/PP 172   Anubias bartei broad leaf.jpg"
  },
  {
    "id": "potted-bacopa-pp-02-bacopa-monnieri-scalaped-edge-leaf",
    "name": "Bacopa monnieri scalaped  edge leaf",
    "code": "PP 02",
    "category": "potted",
    "subcategory": "bacopa",
    "imagePath": "/plants/potted/bacopa/PP 02    Bacopa monnieri scalaped  edge leaf.jpg"
  },
  {
    "id": "potted-bacopa-pp-05-bacopa-caroliniana",
    "name": "Bacopa caroliniana",
    "code": "PP 05",
    "category": "potted",
    "subcategory": "bacopa",
    "imagePath": "/plants/potted/bacopa/PP 05   Bacopa caroliniana.jpg"
  },
  {
    "id": "potted-bacopa-pp-06-bacopa-monnieri",
    "name": "Bacopa monnieri",
    "code": "PP 06",
    "category": "potted",
    "subcategory": "bacopa",
    "imagePath": "/plants/potted/bacopa/PP 06   Bacopa monnieri.jpg"
  },
  {
    "id": "potted-bacopa-pp-06-bacopa-monnieri4",
    "name": "Bacopa monnieri4",
    "code": "PP 06",
    "category": "potted",
    "subcategory": "bacopa",
    "imagePath": "/plants/potted/bacopa/PP 06   Bacopa monnieri4.jpg"
  },
  {
    "id": "potted-bacopa-pp-145-bacopa-lanigera-variegata",
    "name": "Bacopa lanigera  variegata",
    "code": "PP 145",
    "category": "potted",
    "subcategory": "bacopa",
    "imagePath": "/plants/potted/bacopa/PP 145   Bacopa lanigera  variegata.jpg"
  },
  {
    "id": "potted-cabumba-pp-08-cabumba-aquatica",
    "name": "Cabumba aquatica",
    "code": "PP 08",
    "category": "potted",
    "subcategory": "cabumba",
    "imagePath": "/plants/potted/cabumba/PP 08   Cabumba aquatica.jpg"
  },
  {
    "id": "potted-cabumba-pp-08-cabumba-carolina",
    "name": "Cabumba carolina",
    "code": "PP 08",
    "category": "potted",
    "subcategory": "cabumba",
    "imagePath": "/plants/potted/cabumba/PP 08   Cabumba carolina.jpg"
  },
  {
    "id": "potted-cabumba-pp-187-cabumba-piauhyensis",
    "name": "Cabumba piauhyensis",
    "code": "PP 187",
    "category": "potted",
    "subcategory": "cabumba",
    "imagePath": "/plants/potted/cabumba/PP 187 Cabumba piauhyensis.jpg"
  },
  {
    "id": "potted-cryptocoryne-pp-09-cryptocoryne-becketii-c2",
    "name": "Cryptocoryne becketii c2",
    "code": "PP 09",
    "category": "potted",
    "subcategory": "cryptocoryne",
    "imagePath": "/plants/potted/cryptocoryne/PP 09  Cryptocoryne becketii c2.jpg"
  },
  {
    "id": "potted-cryptocoryne-pp-09-cryptocoryne-becketii",
    "name": "Cryptocoryne becketii",
    "code": "PP 09",
    "category": "potted",
    "subcategory": "cryptocoryne",
    "imagePath": "/plants/potted/cryptocoryne/PP 09  Cryptocoryne becketii.jpg"
  },
  {
    "id": "potted-cryptocoryne-pp-12-cryptocoryne-lucens",
    "name": "Cryptocoryne lucens",
    "code": "PP 12",
    "category": "potted",
    "subcategory": "cryptocoryne",
    "imagePath": "/plants/potted/cryptocoryne/PP 12  Cryptocoryne lucens.jpg"
  },
  {
    "id": "potted-cryptocoryne-pp-13-cryptpcoryne-parva",
    "name": "Cryptpcoryne parva",
    "code": "PP 13",
    "category": "potted",
    "subcategory": "cryptocoryne",
    "imagePath": "/plants/potted/cryptocoryne/PP 13   Cryptpcoryne parva.jpg"
  },
  {
    "id": "potted-cryptocoryne-pp-14-cryptocoryne-petchii",
    "name": "Cryptocoryne petchii",
    "code": "PP 14",
    "category": "potted",
    "subcategory": "cryptocoryne",
    "imagePath": "/plants/potted/cryptocoryne/PP 14 Cryptocoryne petchii.jpg"
  },
  {
    "id": "potted-cryptocoryne-pp-15-cryptocoryne-wenditi",
    "name": "Cryptocoryne wenditi",
    "code": "PP 15",
    "category": "potted",
    "subcategory": "cryptocoryne",
    "imagePath": "/plants/potted/cryptocoryne/PP 15   Cryptocoryne wenditi .jpg"
  },
  {
    "id": "potted-cryptocoryne-pp-173-cryptocoryne-wenditi-red-c1",
    "name": "Cryptocoryne wenditi red c1",
    "code": "PP 173",
    "category": "potted",
    "subcategory": "cryptocoryne",
    "imagePath": "/plants/potted/cryptocoryne/PP 173  Cryptocoryne wenditi red c1.jpg"
  },
  {
    "id": "potted-cryptocoryne-pp-174-cryptocoryne-willisi",
    "name": "Cryptocoryne willisi",
    "code": "PP 174",
    "category": "potted",
    "subcategory": "cryptocoryne",
    "imagePath": "/plants/potted/cryptocoryne/PP 174  Cryptocoryne willisi.jpg"
  },
  {
    "id": "potted-cryptocoryne-pp-189-cryptocoryne-pygmia",
    "name": "Cryptocoryne pygmia",
    "code": "PP 189",
    "category": "potted",
    "subcategory": "cryptocoryne",
    "imagePath": "/plants/potted/cryptocoryne/PP 189  Cryptocoryne pygmia.jpg"
  },
  {
    "id": "potted-cryptocoryne-pp-190-cryptocoryne-wenditi-brown",
    "name": "Cryptocoryne wenditi brown",
    "code": "PP 190",
    "category": "potted",
    "subcategory": "cryptocoryne",
    "imagePath": "/plants/potted/cryptocoryne/PP 190 Cryptocoryne wenditi brown.jpg"
  },
  {
    "id": "potted-cryptocoryne-pp-65-cryptocoryen-nevillii",
    "name": "Cryptocoryen nevillii",
    "code": "PP 65",
    "category": "potted",
    "subcategory": "cryptocoryne",
    "imagePath": "/plants/potted/cryptocoryne/PP 65   Cryptocoryen nevillii.jpg"
  },
  {
    "id": "potted-cryptocoryne-pp-68-cryotocoryne-wendtii-broad-leaf",
    "name": "Cryotocoryne wendtii  broad leaf",
    "code": "PP 68",
    "category": "potted",
    "subcategory": "cryptocoryne",
    "imagePath": "/plants/potted/cryptocoryne/PP 68  Cryotocoryne wendtii  broad leaf.jpg"
  },
  {
    "id": "potted-cryptocoryne-pp-69-cryptocoryne-wendtii-mioya",
    "name": "Cryptocoryne wendtii mioya",
    "code": "PP 69",
    "category": "potted",
    "subcategory": "cryptocoryne",
    "imagePath": "/plants/potted/cryptocoryne/PP 69  Cryptocoryne wendtii mioya.jpg"
  },
  {
    "id": "potted-echinodorus-pp-116-echinodorus-subulatus",
    "name": "Echinodorus subulatus",
    "code": "PP 116",
    "category": "potted",
    "subcategory": "echinodorus",
    "imagePath": "/plants/potted/echinodorus/PP 116   Echinodorus subulatus.jpg"
  },
  {
    "id": "potted-echinodorus-pp-118-echinodorus-ozelot-c1",
    "name": "Echinodorus ozelot c1",
    "code": "PP 118",
    "category": "potted",
    "subcategory": "echinodorus",
    "imagePath": "/plants/potted/echinodorus/PP 118  Echinodorus ozelot c1.jpg"
  },
  {
    "id": "potted-echinodorus-pp-118-echinodorus-ozelot",
    "name": "Echinodorus ozelot",
    "code": "PP 118",
    "category": "potted",
    "subcategory": "echinodorus",
    "imagePath": "/plants/potted/echinodorus/PP 118  Echinodorus ozelot.jpg"
  },
  {
    "id": "potted-echinodorus-pp-123-echinodorus-rosea",
    "name": "Echinodorus rosea",
    "code": "PP 123",
    "category": "potted",
    "subcategory": "echinodorus",
    "imagePath": "/plants/potted/echinodorus/PP 123  Echinodorus rosea.jpg"
  },
  {
    "id": "potted-echinodorus-pp-16-echinodorus-amazonicus",
    "name": "Echinodorus amazonicus",
    "code": "PP 16",
    "category": "potted",
    "subcategory": "echinodorus",
    "imagePath": "/plants/potted/echinodorus/PP 16  Echinodorus amazonicus.jpg"
  },
  {
    "id": "potted-echinodorus-pp-17-echinodorus-cordifolius",
    "name": "Echinodorus cordifolius",
    "code": "PP 17",
    "category": "potted",
    "subcategory": "echinodorus",
    "imagePath": "/plants/potted/echinodorus/PP 17  Echinodorus cordifolius.jpg"
  },
  {
    "id": "potted-echinodorus-pp-18-echinodorus-marblequeen",
    "name": "Echinodorus marblequeen",
    "code": "PP 18",
    "category": "potted",
    "subcategory": "echinodorus",
    "imagePath": "/plants/potted/echinodorus/PP 18   Echinodorus marblequeen.jpg"
  },
  {
    "id": "potted-echinodorus-pp-52-echinodorus-leperd",
    "name": "Echinodorus leperd",
    "code": "PP 52",
    "category": "potted",
    "subcategory": "echinodorus",
    "imagePath": "/plants/potted/echinodorus/PP 52   Echinodorus leperd.jpg"
  },
  {
    "id": "potted-echinodorus-pp-52-echinodorus-leperd3",
    "name": "Echinodorus leperd3",
    "code": "PP 52",
    "category": "potted",
    "subcategory": "echinodorus",
    "imagePath": "/plants/potted/echinodorus/PP 52  Echinodorus leperd3.jpg"
  },
  {
    "id": "potted-echinodorus-pp-70-echinodorus-bleheri",
    "name": "Echinodorus bleheri",
    "code": "PP 70",
    "category": "potted",
    "subcategory": "echinodorus",
    "imagePath": "/plants/potted/echinodorus/PP 70   Echinodorus bleheri.jpg"
  },
  {
    "id": "potted-echinodorus-pp-91-echinodorus-grisebachii-tropica",
    "name": "Echinodorus grisebachii  Tropica",
    "code": "PP 91",
    "category": "potted",
    "subcategory": "echinodorus",
    "imagePath": "/plants/potted/echinodorus/PP 91  Echinodorus grisebachii  Tropica.jpg"
  },
  {
    "id": "potted-echinodorus-pp-97-echinodorus-quadricostatus",
    "name": "Echinodorus quadricostatus",
    "code": "PP 97",
    "category": "potted",
    "subcategory": "echinodorus",
    "imagePath": "/plants/potted/echinodorus/PP 97   Echinodorus quadricostatus.jpg"
  },
  {
    "id": "potted-hydrocotyle-pp-103-hydrocotyle-tripartita-japan",
    "name": "Hydrocotyle tripartita  Japan",
    "code": "PP 103",
    "category": "potted",
    "subcategory": "hydrocotyle",
    "imagePath": "/plants/potted/hydrocotyle/PP 103  Hydrocotyle tripartita  Japan.jpg"
  },
  {
    "id": "potted-hydrocotyle-pp-159-hydrocotyle-leucocephala",
    "name": "Hydrocotyle leucocephala",
    "code": "PP 159",
    "category": "potted",
    "subcategory": "hydrocotyle",
    "imagePath": "/plants/potted/hydrocotyle/PP 159   Hydrocotyle leucocephala.jpg"
  },
  {
    "id": "potted-hydrocotyle-pp-24-hydrocotyle-verticillata",
    "name": "Hydrocotyle verticillata",
    "code": "PP 24",
    "category": "potted",
    "subcategory": "hydrocotyle",
    "imagePath": "/plants/potted/hydrocotyle/PP 24  Hydrocotyle verticillata.jpg"
  },
  {
    "id": "potted-hygrophilla-pp-131-hygrophila-corymbosa-via-siamensis",
    "name": "Hygrophila corymbosa via siamensis",
    "code": "PP 131",
    "category": "potted",
    "subcategory": "Hygrophilla",
    "imagePath": "/plants/potted/Hygrophilla/PP 131   Hygrophila corymbosa via siamensis.jpg"
  },
  {
    "id": "potted-hygrophilla-pp-153-hygrophila-sp-parawitota",
    "name": "Hygrophila sp. Parawitota",
    "code": "PP 153",
    "category": "potted",
    "subcategory": "Hygrophilla",
    "imagePath": "/plants/potted/Hygrophilla/PP 153   Hygrophila sp. Parawitota.jpg"
  },
  {
    "id": "potted-hygrophilla-pp-175-hygrophila-corymbosa-mini",
    "name": "Hygrophila corymbosa mini",
    "code": "PP 175",
    "category": "potted",
    "subcategory": "Hygrophilla",
    "imagePath": "/plants/potted/Hygrophilla/PP 175   Hygrophila corymbosa mini.jpg"
  },
  {
    "id": "potted-hygrophilla-pp-26-hygrophila-polysperma",
    "name": "Hygrophila polysperma",
    "code": "PP 26",
    "category": "potted",
    "subcategory": "Hygrophilla",
    "imagePath": "/plants/potted/Hygrophilla/PP 26   Hygrophila polysperma.jpg"
  },
  {
    "id": "potted-hygrophilla-pp-28-hygrophila-stricta",
    "name": "Hygrophila stricta",
    "code": "PP 28",
    "category": "potted",
    "subcategory": "Hygrophilla",
    "imagePath": "/plants/potted/Hygrophilla/PP 28   Hygrophila stricta.jpg"
  },
  {
    "id": "potted-hygrophilla-pp-29-hygrophila-difformis",
    "name": "Hygrophila  difformis",
    "code": "PP 29",
    "category": "potted",
    "subcategory": "Hygrophilla",
    "imagePath": "/plants/potted/Hygrophilla/PP 29   Hygrophila  difformis.jpg"
  },
  {
    "id": "potted-hygrophilla-pp-35-hygrophilla-lancea-arguaia",
    "name": "Hygrophilla lancea  Arguaia",
    "code": "PP 35",
    "category": "potted",
    "subcategory": "Hygrophilla",
    "imagePath": "/plants/potted/Hygrophilla/PP 35   Hygrophilla lancea  Arguaia.jpg"
  },
  {
    "id": "potted-hygrophilla-pp-45-hygrophilla-corymbosa",
    "name": "Hygrophilla corymbosa",
    "code": "PP 45",
    "category": "potted",
    "subcategory": "Hygrophilla",
    "imagePath": "/plants/potted/Hygrophilla/PP 45     Hygrophilla corymbosa.jpg"
  },
  {
    "id": "potted-hygrophilla-pp-77-hygrophilla-pinatafida",
    "name": "Hygrophilla pinatafida",
    "code": "PP 77",
    "category": "potted",
    "subcategory": "Hygrophilla",
    "imagePath": "/plants/potted/Hygrophilla/PP 77  Hygrophilla pinatafida.jpg"
  },
  {
    "id": "potted-hygrophilla-pp-98-hygrophila-rosanervig",
    "name": "Hygrophila Rosanervig",
    "code": "PP 98",
    "category": "potted",
    "subcategory": "Hygrophilla",
    "imagePath": "/plants/potted/Hygrophilla/PP 98   Hygrophila Rosanervig.jpg"
  },
  {
    "id": "potted-ludwigia-pp-104-ludwigia-rubin-c1",
    "name": "Ludwigia  Rubin C1",
    "code": "PP 104",
    "category": "potted",
    "subcategory": "ludwigia",
    "imagePath": "/plants/potted/ludwigia/PP 104  Ludwigia  Rubin C1.jpg"
  },
  {
    "id": "potted-ludwigia-pp-104-ludwigia-rubin",
    "name": "Ludwigia  rubin",
    "code": "PP 104",
    "category": "potted",
    "subcategory": "ludwigia",
    "imagePath": "/plants/potted/ludwigia/PP 104  Ludwigia  rubin.jpg"
  },
  {
    "id": "potted-ludwigia-pp-110-ludwigia-super-red",
    "name": "Ludwigia super red",
    "code": "PP 110",
    "category": "potted",
    "subcategory": "ludwigia",
    "imagePath": "/plants/potted/ludwigia/PP 110   Ludwigia super red.jpg"
  },
  {
    "id": "potted-ludwigia-pp-121-ludwigia-varigated",
    "name": "Ludwigia varigated",
    "code": "PP 121",
    "category": "potted",
    "subcategory": "ludwigia",
    "imagePath": "/plants/potted/ludwigia/PP 121   Ludwigia varigated.jpg"
  },
  {
    "id": "potted-ludwigia-pp-136-ludwigia-repense",
    "name": "Ludwigia repense",
    "code": "PP 136",
    "category": "potted",
    "subcategory": "ludwigia",
    "imagePath": "/plants/potted/ludwigia/PP 136   Ludwigia repense.jpg"
  },
  {
    "id": "potted-ludwigia-pp-146-ludwigia-aracuata",
    "name": "Ludwigia aracuata",
    "code": "PP 146",
    "category": "potted",
    "subcategory": "ludwigia",
    "imagePath": "/plants/potted/ludwigia/PP 146  Ludwigia aracuata.jpg"
  },
  {
    "id": "potted-ludwigia-pp-149-ludwigia-glandulosa",
    "name": "Ludwigia glandulosa",
    "code": "PP 149",
    "category": "potted",
    "subcategory": "ludwigia",
    "imagePath": "/plants/potted/ludwigia/PP 149   Ludwigia glandulosa.jpg"
  },
  {
    "id": "potted-ludwigia-pp-155-ludwigia-peruensis",
    "name": "Ludwigia peruensis",
    "code": "PP 155",
    "category": "potted",
    "subcategory": "ludwigia",
    "imagePath": "/plants/potted/ludwigia/PP 155   Ludwigia peruensis.jpg"
  },
  {
    "id": "potted-ludwigia-pp-180-ludwigia-brevis-c1",
    "name": "Ludwigia brevis C1",
    "code": "PP 180",
    "category": "potted",
    "subcategory": "ludwigia",
    "imagePath": "/plants/potted/ludwigia/PP 180  Ludwigia brevis C1.jpg"
  },
  {
    "id": "potted-ludwigia-pp-33-ludwigia-ovalis",
    "name": "Ludwigia ovalis",
    "code": "PP 33",
    "category": "potted",
    "subcategory": "ludwigia",
    "imagePath": "/plants/potted/ludwigia/PP 33  Ludwigia ovalis.jpg"
  },
  {
    "id": "potted-root-pp-01-ammaniya-grasilis",
    "name": "Ammaniya grasilis",
    "code": "PP 01",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 01   Ammaniya grasilis.jpg"
  },
  {
    "id": "potted-root-pp-10-ceratophyllum-demersum-c1",
    "name": "Ceratophyllum demersum  c1",
    "code": "PP 10",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 10  Ceratophyllum demersum  c1.jpg"
  },
  {
    "id": "potted-root-pp-129-pogostemon-stellata-eustralis-c1",
    "name": "Pogostemon stellata (Eustralis)c1",
    "code": "PP 129",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 129  Pogostemon stellata (Eustralis)c1.jpg"
  },
  {
    "id": "potted-root-pp-129-pogostemon-stellata-eustralis",
    "name": "Pogostemon stellata Eustralis",
    "code": "PP 129",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 129  Pogostemon stellata Eustralis.jpg"
  },
  {
    "id": "potted-root-pp-156-staurogyne-repense",
    "name": "Staurogyne repense",
    "code": "PP 156",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 156  Staurogyne repense.jpg"
  },
  {
    "id": "potted-root-pp-160-proserinaca-pulustris",
    "name": "Proserinaca pulustris",
    "code": "PP 160",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 160  Proserinaca pulustris.jpg"
  },
  {
    "id": "potted-root-pp-163-hemanthus-calithoides-cuba",
    "name": "Hemanthus calithoides Cuba",
    "code": "PP 163",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 163  Hemanthus calithoides Cuba.jpg"
  },
  {
    "id": "potted-root-pp-165-pogostemus-octopus",
    "name": "Pogostemus octopus",
    "code": "PP 165",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 165 Pogostemus octopus.jpg"
  },
  {
    "id": "potted-root-pp-185-ceratophyllum-submersum",
    "name": "Ceratophyllum submersum",
    "code": "PP 185",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 185  Ceratophyllum submersum.jpg"
  },
  {
    "id": "potted-root-pp-19-eleocharis-acicularis",
    "name": "Eleocharis acicularis",
    "code": "PP 19",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 19    Eleocharis acicularis.jpg"
  },
  {
    "id": "potted-root-pp-20-egeria-densa",
    "name": "Egeria densa",
    "code": "PP 20",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 20  Egeria densa.jpg"
  },
  {
    "id": "potted-root-pp-32-limnophila-sessiliflora",
    "name": "Limnophila sessiliflora",
    "code": "PP 32",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 32  Limnophila sessiliflora.jpg"
  },
  {
    "id": "potted-root-pp-34-myriophyllum-mattogrossense",
    "name": "Myriophyllum mattogrossense",
    "code": "PP 34",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 34  Myriophyllum mattogrossense.jpg"
  },
  {
    "id": "potted-root-pp-40-valisneria-gigantia",
    "name": "Valisneria gigantia",
    "code": "PP 40",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 40  Valisneria gigantia.jpg"
  },
  {
    "id": "potted-root-pp-42-valisneriya-amaricana",
    "name": ".Valisneriya amaricana",
    "code": "PP 42",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 42 .Valisneriya amaricana.JPG"
  },
  {
    "id": "potted-root-pp-43-valisneria-nana",
    "name": "Valisneria nana",
    "code": "PP 43",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 43   Valisneria nana.jpg"
  },
  {
    "id": "potted-root-pp-46-myriophyllum-scabratum",
    "name": "Myriophyllum scabratum",
    "code": "PP 46",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 46    Myriophyllum scabratum.jpg"
  },
  {
    "id": "potted-root-pp-49-limnophylla-aromatica",
    "name": "Limnophylla aromatica",
    "code": "PP 49",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 49  Limnophylla aromatica.jpg"
  },
  {
    "id": "potted-root-pp-60-heminthus-micranthemodes",
    "name": "Heminthus micranthemodes",
    "code": "PP 60",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 60   Heminthus micranthemodes.jpg"
  },
  {
    "id": "potted-root-pp-71-eleocharis-vivipara",
    "name": "Eleocharis vivipara",
    "code": "PP 71",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 71  Eleocharis vivipara.jpg"
  },
  {
    "id": "potted-root-pp-73-lilaeopsis-novae-zelandiae",
    "name": "Lilaeopsis novae-zelandiae",
    "code": "PP 73",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 73   Lilaeopsis novae-zelandiae.jpg"
  },
  {
    "id": "potted-root-pp-75-lobelia-cardinalis",
    "name": "Lobelia cardinalis",
    "code": "PP 75",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 75   Lobelia cardinalis.jpg"
  },
  {
    "id": "potted-root-pp-80-bolbris-heudelotii",
    "name": "Bolbris heudelotii",
    "code": "PP 80",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 80  Bolbris heudelotii.jpg"
  },
  {
    "id": "potted-root-pp-80-microsoium-peteropus",
    "name": "Microsoium peteropus",
    "code": "PP 80",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 80  Microsoium peteropus.jpg"
  },
  {
    "id": "potted-root-pp-81-microsorium-windelav",
    "name": "Microsorium windelav",
    "code": "PP 81",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 81   Microsorium windelav.jpg"
  },
  {
    "id": "potted-root-pp-82-microsoium-peteropus",
    "name": "Microsoium peteropus",
    "code": "PP 82",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 82  Microsoium peteropus.jpg"
  },
  {
    "id": "potted-root-pp-94-tiger-lotus-red",
    "name": "Tiger lotus  red",
    "code": "PP 94",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 94  Tiger lotus  red.jpg"
  },
  {
    "id": "potted-root-pp-94-tiger-lotus-green",
    "name": "Tiger lotus green",
    "code": "PP 94",
    "category": "potted",
    "subcategory": null,
    "imagePath": "/plants/potted/PP 94  Tiger lotus green.jpg"
  },
  {
    "id": "potted-rotala-pp-107-rotala-wallichi",
    "name": "Rotala wallichi",
    "code": "PP 107",
    "category": "potted",
    "subcategory": "rotala",
    "imagePath": "/plants/potted/rotala/PP 107   Rotala wallichi.jpg"
  },
  {
    "id": "potted-rotala-pp-111-rotala-najeshan",
    "name": "Rotala najeshan",
    "code": "PP 111",
    "category": "potted",
    "subcategory": "rotala",
    "imagePath": "/plants/potted/rotala/PP 111   Rotala najeshan.jpg"
  },
  {
    "id": "potted-rotala-pp-125-rotala-macranda",
    "name": "Rotala macranda",
    "code": "PP 125",
    "category": "potted",
    "subcategory": "rotala",
    "imagePath": "/plants/potted/rotala/PP 125    Rotala macranda.jpg"
  },
  {
    "id": "potted-rotala-pp-126-red-rotala-c1",
    "name": "Red rotala  c1",
    "code": "PP 126",
    "category": "potted",
    "subcategory": "rotala",
    "imagePath": "/plants/potted/rotala/PP 126  Red rotala  c1.jpg"
  },
  {
    "id": "potted-rotala-pp-140-rotala-species-green",
    "name": "Rotala species green",
    "code": "PP 140",
    "category": "potted",
    "subcategory": "rotala",
    "imagePath": "/plants/potted/rotala/PP 140    Rotala species green.jpg"
  },
  {
    "id": "potted-rotala-pp-151-rotala-macranda-gient",
    "name": "Rotala macranda gient",
    "code": "PP 151",
    "category": "potted",
    "subcategory": "rotala",
    "imagePath": "/plants/potted/rotala/PP 151  Rotala macranda gient.jpg"
  },
  {
    "id": "potted-rotala-pp-168-rotala-hara",
    "name": "Rotala hara",
    "code": "PP 168",
    "category": "potted",
    "subcategory": "rotala",
    "imagePath": "/plants/potted/rotala/PP 168  Rotala hara.jpg"
  },
  {
    "id": "potted-rotala-pp-187-ludwigia-aracuata-red",
    "name": "Ludwigia aracuata RED",
    "code": "PP 187",
    "category": "potted",
    "subcategory": "rotala",
    "imagePath": "/plants/potted/rotala/PP 187  Ludwigia aracuata RED.jpg"
  },
  {
    "id": "potted-rotala-pp-187-rotala-rotundifolia-orange",
    "name": "Rotala rotundifolia orange",
    "code": "PP 187",
    "category": "potted",
    "subcategory": "rotala",
    "imagePath": "/plants/potted/rotala/PP 187  Rotala rotundifolia orange.jpg"
  },
  {
    "id": "potted-rotala-pp-188-rotala-rotundifolia-blood-red",
    "name": "Rotala rotundifolia blood red",
    "code": "PP 188",
    "category": "potted",
    "subcategory": "rotala",
    "imagePath": "/plants/potted/rotala/PP 188   Rotala rotundifolia blood red.jpg"
  },
  {
    "id": "potted-rotala-pp-38-rotala-rotundifolia",
    "name": "Rotala rotundifolia",
    "code": "PP 38",
    "category": "potted",
    "subcategory": "rotala",
    "imagePath": "/plants/potted/rotala/PP 38   Rotala rotundifolia.jpg"
  },
  {
    "id": "potted-terarium-dracena-pp-55-dracena-sandriyana-white",
    "name": "Dracena sandriyana  white",
    "code": "PP 55",
    "category": "potted",
    "subcategory": "terarium/dracena",
    "imagePath": "/plants/potted/terarium/dracena/PP 55   Dracena sandriyana  white.jpg"
  },
  {
    "id": "potted-terarium-dracena-pp-57-dracena-sandriyana-victory",
    "name": "Dracena sandriyana victory",
    "code": "PP 57",
    "category": "potted",
    "subcategory": "terarium/dracena",
    "imagePath": "/plants/potted/terarium/dracena/PP 57   Dracena sandriyana victory.jpg"
  },
  {
    "id": "potted-terarium-dracena-pp-90-dracena-sandriyana-green",
    "name": "Dracena sandriyana green",
    "code": "PP 90",
    "category": "potted",
    "subcategory": "terarium/dracena",
    "imagePath": "/plants/potted/terarium/dracena/PP 90   Dracena sandriyana green.jpg"
  },
  {
    "id": "potted-terarium-dracena-pp-90-dracena-varigated",
    "name": "Dracena varigated",
    "code": "PP 90",
    "category": "potted",
    "subcategory": "terarium/dracena",
    "imagePath": "/plants/potted/terarium/dracena/PP 90  Dracena varigated.jpg"
  },
  {
    "id": "potted-terarium-ophiopogon-pp-138-ophiopogon-japonica",
    "name": "Ophiopogon japonica",
    "code": "PP 138",
    "category": "potted",
    "subcategory": "terarium/ophiopogon",
    "imagePath": "/plants/potted/terarium/ophiopogon/PP 138  Ophiopogon japonica.jpg"
  },
  {
    "id": "potted-terarium-ophiopogon-pp-139-ophiopogon-jaburan-variegatus",
    "name": "Ophiopogon jaburan  Variegatus",
    "code": "PP 139",
    "category": "potted",
    "subcategory": "terarium/ophiopogon",
    "imagePath": "/plants/potted/terarium/ophiopogon/PP 139  Ophiopogon jaburan  Variegatus.jpg"
  },
  {
    "id": "potted-terarium-ophiopogon-pp-144-ophiopogon-japonica-kyoto",
    "name": "Ophiopogon japonica kyoto",
    "code": "PP 144",
    "category": "potted",
    "subcategory": "terarium/ophiopogon",
    "imagePath": "/plants/potted/terarium/ophiopogon/PP 144  Ophiopogon japonica kyoto.jpg"
  },
  {
    "id": "potted-terarium-ophiopogon-pp-148-ophiopogon-jaburan",
    "name": "Ophiopogon jaburan",
    "code": "PP 148",
    "category": "potted",
    "subcategory": "terarium/ophiopogon",
    "imagePath": "/plants/potted/terarium/ophiopogon/PP 148  Ophiopogon jaburan .jpg"
  },
  {
    "id": "potted-terarium-syngonium-pp-157-syngonium-sourtherns-star",
    "name": "Syngonium sourtherns star",
    "code": "PP 157",
    "category": "potted",
    "subcategory": "terarium/syngonium",
    "imagePath": "/plants/potted/terarium/syngonium/PP 157  Syngonium sourtherns star.jpg"
  },
  {
    "id": "potted-terarium-syngonium-pp-184-syngonium-pink-rose",
    "name": "Syngonium pink rose",
    "code": "PP 184",
    "category": "potted",
    "subcategory": "terarium/syngonium",
    "imagePath": "/plants/potted/terarium/syngonium/PP 184   Syngonium pink rose.jpg"
  },
  {
    "id": "potted-terarium-syngonium-pp-186-syngonium-snow-white",
    "name": "Syngonium snow white",
    "code": "PP 186",
    "category": "potted",
    "subcategory": "terarium/syngonium",
    "imagePath": "/plants/potted/terarium/syngonium/PP 186  Syngonium snow white.jpg"
  },
  {
    "id": "potted-terarium-syngonium-pp-58-syngonium-podophyllum",
    "name": "Syngonium podophyllum",
    "code": "PP 58",
    "category": "potted",
    "subcategory": "terarium/syngonium",
    "imagePath": "/plants/potted/terarium/syngonium/PP 58    Syngonium podophyllum.jpg"
  },
  {
    "id": "potted-terarium-syngonium-pp-59-syngonium-whitebutterfly",
    "name": "Syngonium whitebutterfly",
    "code": "PP 59",
    "category": "potted",
    "subcategory": "terarium/syngonium",
    "imagePath": "/plants/potted/terarium/syngonium/PP 59   Syngonium whitebutterfly.jpg"
  },
  {
    "id": "bunches-root-bunch-10-bunch-10",
    "name": "BUNCH 10",
    "code": "BUNCH 10",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 10.jpg"
  },
  {
    "id": "bunches-root-bunch-11-bunch-11",
    "name": "BUNCH 11",
    "code": "BUNCH 11",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 11.jpg"
  },
  {
    "id": "bunches-root-bunch-12-bunch-12",
    "name": "BUNCH 12",
    "code": "BUNCH 12",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 12.jpg"
  },
  {
    "id": "bunches-root-bunch-13-bunch-13",
    "name": "BUNCH 13",
    "code": "BUNCH 13",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 13.jpg"
  },
  {
    "id": "bunches-root-bunch-14-bunch-14",
    "name": "BUNCH 14",
    "code": "BUNCH 14",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 14.jpg"
  },
  {
    "id": "bunches-root-bunch-15-bunch-15",
    "name": "BUNCH 15",
    "code": "BUNCH 15",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 15.jpg"
  },
  {
    "id": "bunches-root-bunch-16-bunch-16",
    "name": "BUNCH 16",
    "code": "BUNCH 16",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 16.jpg"
  },
  {
    "id": "bunches-root-bunch-17-bunch-17",
    "name": "BUNCH 17",
    "code": "BUNCH 17",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 17.jpg"
  },
  {
    "id": "bunches-root-bunch-18-bunch-18",
    "name": "BUNCH 18",
    "code": "BUNCH 18",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 18.jpg"
  },
  {
    "id": "bunches-root-bunch-19-bunch-19",
    "name": "BUNCH 19",
    "code": "BUNCH 19",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 19.jpg"
  },
  {
    "id": "bunches-root-bunch-2-bunch-2",
    "name": "BUNCH 2",
    "code": "BUNCH 2",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 2.jpg"
  },
  {
    "id": "bunches-root-bunch-20-bunch-20",
    "name": "BUNCH 20",
    "code": "BUNCH 20",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 20.jpg"
  },
  {
    "id": "bunches-root-bunch-21-bunch-21",
    "name": "BUNCH 21",
    "code": "BUNCH 21",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 21.jpg"
  },
  {
    "id": "bunches-root-bunch-22-bunch-22",
    "name": "BUNCH 22",
    "code": "BUNCH 22",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 22.jpg"
  },
  {
    "id": "bunches-root-bunch-23-bunch-23",
    "name": "BUNCH 23",
    "code": "BUNCH 23",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 23.jpg"
  },
  {
    "id": "bunches-root-bunch-24-bunch-24",
    "name": "BUNCH 24",
    "code": "BUNCH 24",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 24.jpg"
  },
  {
    "id": "bunches-root-bunch-25-bunch-25",
    "name": "BUNCH 25",
    "code": "BUNCH 25",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 25.jpg"
  },
  {
    "id": "bunches-root-bunch-26-bunch-26",
    "name": "BUNCH 26",
    "code": "BUNCH 26",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 26.jpg"
  },
  {
    "id": "bunches-root-bunch-27-bunch-27",
    "name": "BUNCH 27",
    "code": "BUNCH 27",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 27.jpg"
  },
  {
    "id": "bunches-root-bunch-4-bunch-4",
    "name": "BUNCH 4",
    "code": "BUNCH 4",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 4.jpg"
  },
  {
    "id": "bunches-root-bunch-5-bunch-5",
    "name": "BUNCH 5",
    "code": "BUNCH 5",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 5.jpg"
  },
  {
    "id": "bunches-root-bunch-6-bunch-6",
    "name": "BUNCH 6",
    "code": "BUNCH 6",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 6.jpg"
  },
  {
    "id": "bunches-root-bunch-7-bunch-7",
    "name": "BUNCH 7",
    "code": "BUNCH 7",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 7.jpg"
  },
  {
    "id": "bunches-root-bunch-8-bunch-8",
    "name": "BUNCH 8",
    "code": "BUNCH 8",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 8.jpg"
  },
  {
    "id": "bunches-root-bunch-9-bunch-9",
    "name": "BUNCH 9",
    "code": "BUNCH 9",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunch 9.jpg"
  },
  {
    "id": "bunches-root-bunch-es-1",
    "name": "es 1",
    "code": "BUNCH",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunches 1.jpg"
  },
  {
    "id": "bunches-root-bunch-es-3",
    "name": "es 3",
    "code": "BUNCH",
    "category": "bunches",
    "subcategory": null,
    "imagePath": "/plants/bunches/bunches 3.jpg"
  },
  {
    "id": "gallery-root-lab",
    "name": "lab",
    "code": "",
    "category": "gallery",
    "subcategory": null,
    "imagePath": "/plants/gallery/lab.jpg"
  },
  {
    "id": "gallery-root-tc-assorted-2",
    "name": "assorted 2",
    "code": "TC",
    "category": "gallery",
    "subcategory": null,
    "imagePath": "/plants/gallery/tc assorted 2.jpg"
  },
  {
    "id": "gallery-root-tc-assorted",
    "name": "assorted",
    "code": "TC",
    "category": "gallery",
    "subcategory": null,
    "imagePath": "/plants/gallery/tc assorted.jpg"
  },
  {
    "id": "gallery-root-dsc0743",
    "name": "_DSC0743",
    "code": "",
    "category": "gallery",
    "subcategory": null,
    "imagePath": "/plants/gallery/_DSC0743.jpg"
  },
  {
    "id": "mosses-root-m0-10-versicularia-ferrier-weeping-moss",
    "name": "Versicularia ferrier weeping moss",
    "code": "M0 10",
    "category": "mosses",
    "subcategory": null,
    "imagePath": "/plants/mosses/M0 10    Versicularia ferrier weeping moss.jpg"
  },
  {
    "id": "mosses-root-mo-01-vesicularia-dubyana",
    "name": "Vesicularia dubyana",
    "code": "MO 01",
    "category": "mosses",
    "subcategory": null,
    "imagePath": "/plants/mosses/MO 01  Vesicularia dubyana .jpg"
  },
  {
    "id": "mosses-root-mo-07-versicularia-christms-moss",
    "name": "Versicularia  christms moss",
    "code": "MO 07",
    "category": "mosses",
    "subcategory": null,
    "imagePath": "/plants/mosses/MO 07   Versicularia  christms moss .jpg"
  },
  {
    "id": "mosses-root-mo-14-riccia-fluitans",
    "name": "Riccia fluitans",
    "code": "MO 14",
    "category": "mosses",
    "subcategory": null,
    "imagePath": "/plants/mosses/MO 14  Riccia fluitans .jpg"
  }
];
